openapi: 3.0.0
info: # info about the project
  title: new Swagger documentation
  description: return some data
  version: 1.1.0

servers:
  # server url
  - url: `{protocol}://localhost:1000/api/{version}`
    description: for local host server
    variables:
      # versions of api
      version:
        enum:
          - v1
          - v2
        default: v1
      #  protocols 
      protocol:
        enum:
          - http
          - https
        default: http

# for auth
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer
