openapi: 3.0.0
info: # info about the project
  title: T-shirt Store API
  description: return product / user data
  version: 1.1.0

servers:
  # server url
  - url: "{protocol}://localhost:1000/api/{version}" 
    description: for local host server
    variables:
      # versions of api
      version:
        enum:
          - v1
          - v2
        default: v1
      #  protocols 
      protocol:
        enum:
          - http
          - https
        default: http

# for auth
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

# routes
paths:
  /:
    get:
    # grouping the paths
      tags:
        - Greetings
      summary: return a greeting message
      responses:
        200:
          description: Success, OK
          content:
            application/json:
              schema:
                type: string
                example: "greetingString"
        400:
          description: Bad request
        500:
          description: Internal Server Error

  /user/signup:
    post:
      tags:
        - User
      summary: create a new user inside the database
      # type of data taken
      consumes:
        - multipart/form-data
      # type of output produced
      produces:
        - application/json
      # params passed to add new course
      requestBody:
        # all values are required
        required: true
        # content 
        content:
          multipart/form-data:
            schema:
              # takes an object
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                photo:
                  type: string
                  format: binary
      responses:
        200:
        # return the entered object
          description: Success, OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                  token:
                    type: string
                  user:
                    type: object
                    properties:
                      name:
                        type: string
                      email:
                        type: string
                      role:
                        type: string
                      photo:
                        type: object
                        properties:
                          id:
                            type: string
                          secure_url:
                            type: string
                      createdAt:
                        type: date
        400:
          description: Bad request
        500:
          description: Internal Server Error